apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 4
  template:
    metadata:
        name: new-app
        labels:
          app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx