apiVersion: app/v1
kind: ReplicaSet
metadata:
  name: myapp-replicaset
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      env: production
  replicas: 3
  template:
    metadata:
        name: new-app
        labels:
          app: myapp
    spec:
      containers:
        - name: nginx
          image: nginx